### ISSUE TITLE
mocking support

### ISSUE THREAD

**Issue by zhuoqiang** [snitch-org/snitch#152]
I wonder if snitch support any mocking framework, like [trompeloeil](https://github.com/rollbear/trompeloeil), etc. I could not find any doc on this topic.

**Comment by cschreib** [comment]
Hi! Indeed this in not supported by snitch, and isn't on the roadmap.

**Comment by zhuoqiang** [comment]
> Hi! Indeed this in not supported by snitch, and isn't on the roadmap.

thanks for the reply.

Trompeloeil [says](https://github.com/rollbear/trompeloeil/blob/main/docs/FAQ.md#unit_test_adaptation)

> By default, Trompeloeil reports violations by throwing an exception, explaining the problem in the [what()](http://en.cppreference.com/w/cpp/error/exception/what) string.

Does snitch play well with this reporting mechinism? My gut feeling is that trompeloeil could be used in snitch by default without problem, but I'm not sure on this.

anything possible in snitch could prevent itself from working with Trompeloeil?

**Comment by cschreib** [comment]
That's absolutely fine. Snitch also uses exceptions to report failures in the `REQUIRE(...)` checks, for example. Just make sure that snitch is configured to support exceptions (which is the default configuration). See the readme sectioned about exceptions if you want to know more.

**Comment by cschreib** [comment]
I'll close this, please re-open if you are having difficulties.
