### ISSUE TITLE
--color vs. --colour-mode

### ISSUE THREAD

**Issue by vid512** [snitch-org/snitch#155]
Snitch command line options seem to be mixing US and british spelling of color vs. colour, in option names **--color** and **--colour-mode**. Descriptions of parameters always use spelling "color". Is there any historical reason for this, or just an oversight? It would make sense to stick to single spelling.

Maybe add **--color-mode** as preferred synonym to **--colour-mode**, and keep **--colour-mode** only for backwards compatibility?

**Comment by cschreib** [comment]
It is historical yes; the UK spelling version is provided for command-line compatibility with Catch2 (which allows snitch to use the exact same IDE integrations, so is very important). The snitch native command-line, instead, uses US spelling, which is more prominent in software APIs hence least surprising.
