### ISSUE TITLE
Snitch missing from meson WrapDB

### ISSUE THREAD

**Issue by vid512** [snitch-org/snitch#157]
According to the docs (https://github.com/snitch-org/snitch?tab=readme-ov-file#example-build-configuration-with-meson), snitch should be available in Meson WrapDB, but that doesn't seem to be the case. 

The 'meson wrap install snitch' command says 'ERROR: Wrap snitch not found in wrapdb'. 

Also I don't see 'snitch' in the list of packages: https://mesonbuild.com/Wrapdb-projects.html

**Comment by cschreib** [comment]
Duplicate of https://github.com/snitch-org/snitch/issues/156, closing.
