### ISSUE TITLE
Please use the pre-installed 'doctest' package before fetching it

### ISSUE THREAD

**Issue by yurivict** [snitch-org/snitch#201]
In the ports frameworks fetch is not allowed and is disabled for security reasons.
doctest isn't fetched and isn't found due to ```-DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON```.

**Comment by cschreib** [comment]
Hi! Do I understand correctly that you're asking for a way to use a pre-installed version of `doctest` as an alternative to downloading it on-demand using CMake `FetchContent`? If so, would it be acceptable if we introduced a `SNITCH_USE_SYSTEM_DOCTEST` configuration variable which, if set to `ON`, would bypass `FetchContent` and use `find_package()` instead?

By the way, I have no idea what "ports frameworks" are. Would you care to add more information about this particular use case? Thanks.

**Comment by yurivict** [comment]
> [...] would it be acceptable if we introduced a SNITCH_USE_SYSTEM_DOCTEST configuration variable [...]

Yes, ```SNITCH_USE_SYSTEM_DOCTEST``` should be sufficient.

> By the way, I have no idea what "ports frameworks" are. Would you care to add more information about this particular use case? Thanks.

On modern systems software is installed through binary packages using package manager.
Packages are built from ports. Each port is a collection of instructions how to build this software package, what are its dependencies, etc. Ports framework is a framework which contains relevant recipes for how to build various packages. For example, cmake based software is built using one set of scripts, Python packages are built using there own set of scripts, same for gmake, qmake, etc. There are many ports frameworks: Debian, RPM, Slack, Arch, FreeBSD, OpenBSD, Spack, etc.

Without such frameworks it would be very problematic to install hundreds of thousands of packages with only several commands.

**Comment by cschreib** [comment]
Thank you for the explanations! I will open a PR with the changes later today. 

Can I ask how important this is to you, as in, is this blocking a deployment? Just so I know whether it needs a new release soon once merged. NB: I expected that `FetchContent` would be good enough since `doctest` is only used in the tests, which aren't necessary to use the library.

**Comment by cschreib** [comment]
Merged in https://github.com/snitch-org/snitch/pull/202.
